### ISSUE TITLE
Can't build `libsql_bindgen/examples/encrypt_decrypt` with `wasm32-unknown-unknown`

### ISSUE THREAD

**Issue by L-jasmine** [psarna/libsql_bindgen#1]
I build `libsql_bindgen/examples/encrypt_decrypt` with `cargo build --target wasm32-unknown-unknown` is fail.
Many type is not found. like 
```
error[E0433]: failed to resolve: use of undeclared type `U3`
   --> /home/codespace/.cargo/registry/src/github.com-1ecc6299db9ec823/typenum-1.16.0/src/type_operators.rs:240:14
    |
240 |     let u3 = U3::new();
    |              ^^ use of undeclared type `U3`

error[E0433]: failed to resolve: use of undeclared type `N3`
   --> /home/codespace/.cargo/registry/src/github.com-1ecc6299db9ec823/typenum-1.16.0/src/type_operators.rs:241:14
    |
241 |     let n3 = N3::new();
    |              ^^ use of undeclared type `N3`

Some errors have detailed explanations: E0405, E0412, E0432, E0433, E0463.
For more information about an error, try `rustc --explain E0405`.
error: could not compile `typenum` due to 150 previous errors
```
but `wasm32-wasi` is ok.

**Comment by psarna** [comment]
Looks like the example started rotting, it used to work... I'll validate, fix, and add compiling it to our CI. Thanks for reporting

**Comment by psarna** [comment]
hm, I just tried and it worked just fine, with typenum == 1.16.0 as well.... both with stable and nightly Rust. Meanwhile, could you retry after `cargo clean`, both with `rustup default stable` and `rustup default nightly`? I wonder why it would run in my env and fail in yours.

**Comment by psarna** [comment]
also, what's your OS and cpu architecture?

**Comment by L-jasmine** [comment]
oh sorry, I'm not install wasm32-unknown-unknown.
